### ISSUE TITLE
Always ask for console password when Decrypting

### ISSUE THREAD

**Issue by MakarovCode** [mnipper/serket#1]
Hi, every time I try to 
`Serket.decrypt('text')` 

It ask me for the Private key password.

Here is my initializer/serket.rb and the commands I use to generate the Keys
`#openssl rsa -in mykey.pem -pubout > mykey.pub
# openssl rsa -in key.pem -pubout -out pubkey.pem

Serket.configure do |config|
    config.format = :json

```
path = Rails.root.join('certificates', "dev") unless Rails.env == "production"
path = Rails.root.join('certificates', "pro") if Rails.env == "production"

config.public_key_path = "#{path}/public_key.pem"
config.private_key_path = "#{path}/private_key.pem"
```

end`

And the code I am using in my controller:

`Serket.decrypt(params[:order])`

Thanks in advance

**Comment by MakarovCode** [comment]
Well when I Try when the Keys you provide in the Gem it works, I'm figuring out why my certificates ask for the password every time.

**Comment by mnipper** [comment]
It's common practice to not require a password for your rsa private key when it is accessed with a script such as this.  Please note that this means that you lose the protection a password provides, so if you leak your private key then there is nothing protecting it.  Be sure to lock down the file's permissions on the server and don't check it into your git repo, for example.  Just press enter when it prompts you for a password when generating the key (without entering anything for the password), and that will get you going.

**Comment by MakarovCode** [comment]
Great, thanks for the quick answer!
